### ISSUE TITLE
Example of Run Parameters

### ISSUE THREAD

**Issue by graemeho** [metoceanapi/forecast-api-examples#1]
Please provide similar Golang examples as the Python and Javascript code notes.

**Comment by okey** [comment]
@graemeho We are slowly working on improving this project.

I'm not exactly sure what you need, but there is now a brief golang readme and soon there will be some more golang examples.

**Comment by graemeho** [comment]
@okey Thanks for the clarification. I will be following this project, particularly the golang code, with great interest.

- I am able to run the supplied python examples, so I've verified my api-key 
- Checking to see if something is misconfigured in my golang env / setup 
-  go version + go1.19.4 linux/amd64

**Comment by okey** [comment]
@graemeho Can you clarify what problem you are having?

To run the Golang pointTime example, run `go run . -example pointTime -apikey YOUR_API_KEY_HERE` from a shell inside the golang subdirectory in the repo. Note the ` . ` after `go run`, which is necessary to tell the Go compiler to run on the current directory.

**Comment by graemeho** [comment]
@okey Thank your for your prompt response.
Seeing the results expected now.
